/*CREATE TABLE student (
  ID double NOT NULL,
  NAME varchar(45) DEFAULT NULL,
  AVAILABLE tinyint(4) DEFAULT NULL,
  PRIMARY KEY (ID)
); 

INSERT INTO STUDENT(ID, NAME, AVAILABLE)
VALUES(1, "marry", 1);

INSERT INTO STUDENT(ID, NAME, AVAILABLE)
VALUES(2, "john", 0);

INSERT INTO STUDENT(ID, NAME, AVAILABLE)
VALUES(3, "daisy", 0);

INSERT INTO STUDENT(ID, NAME, AVAILABLE)
VALUES(4, "tom", 1);

INSERT INTO STUDENT(ID, NAME, AVAILABLE)
VALUES(5, "hanh", 1);

*/
